runtime:
  cache_dir: ./.cache/antora
  log:
    failure_level: warn
site:
  title: Containers CI/CD and Benchmarking Training
  url: https://coe-hidalgo2.github.io/
  start_page: training-containers-cicd-benchmarking:training-202503-karolina:index.adoc
  robots: allow
git:
  ensure_git_suffix: false
urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs
  - url: https://github.com/feelpp/course-project
    branches: master
    start_path: docs
  - url: https://github.com/feelpp/benchmarking
    branches: master
    start_path: docs
antora:
  extensions:
  - '@antora/collector-extension'
asciidoc:
  extensions:
  - '@asciidoctor/tabs'
  - '@feelpp/asciidoctor-extensions'
  attributes:
    page-component-order: '!ROOT, *, pdf-converter, epub3-converter, reveal.js-converter, maven-tools, gradle-plugin, asciidoclet, diagram-extension, browser-extension, about'
    page-pagination: ''
    output-dir: public
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    table-caption: false
    table-frame: 'none@'
    table-grid: 'rows@'
    example-caption: false
    listing-caption: false
    hide-uri-scheme: '@'
    url-org: https://github.com/asciidoctor
    url-project: https://asciidoctor.org
ui:
  supplemental_files: ./docs/antora/supplemental-ui
  bundle:
    url: https://github.com/feelpp/antora-ui/releases/download/v0.44/ui-bundle.zip
    snapshot: true # must be set since the prod-latest tag is an alias
output:
  dir: ./public